Repository woocommerce/woocommerce-gateway-paypal-express-checkout, pull requests merged in 2020-04, with the labels that each got.

#696 Use base64_decode on API certificate while creating Credential object
  assets/js/wc-gateway-ppec-settings.js
  includes/abstracts/abstract-wc-gateway-ppec.php
  includes/class-wc-gateway-ppec-settings.php
  includes/settings/settings-ppec.php
Labels: Documentation, [Status] Needs Review

#702 Fix free subscription initial purchases using PayPal Smart Buttons
  includes/class-wc-gateway-ppec-admin-handler.php
  includes/class-wc-gateway-ppec-checkout-handler.php
Labels: [Status] Needs Review

#709 Check for response error message before assigning
  assets/js/wc-gateway-ppec-smart-payment-buttons.js
Labels: [Status] Needs Review

#712 Validate incomplete API credentials fields
  assets/js/wc-gateway-ppec-settings.js
  includes/abstracts/abstract-wc-gateway-ppec.php
  includes/settings/settings-ppec.php
Labels: [Status] Needs Author Reply
