Repository woocommerce/woocommerce-gateway-paypal-express-checkout, pull requests merged in 2020-05, with the labels that each got.

#668 Add support for PayPal JS SDK
  assets/js/dist/fetch-polyfill.min.js
  assets/js/dist/promise-polyfill.min.js
  assets/js/wc-gateway-ppec-settings.js
  assets/js/wc-gateway-ppec-smart-payment-buttons.js
  includes/abstracts/abstract-wc-gateway-ppec.php
  includes/class-wc-gateway-ppec-admin-handler.php
  includes/class-wc-gateway-ppec-cart-handler.php
  includes/class-wc-gateway-ppec-plugin.php
  includes/class-wc-gateway-ppec-rest-client-credential.php
  includes/class-wc-gateway-ppec-rest-client.php
  includes/class-wc-gateway-ppec-session-data.php
  includes/class-wc-gateway-ppec-settings.php
  includes/settings/settings-ppec.php
Labels: Documentation, [Status] In Progress

#707 Allow WC to perform validation when missing fields
  assets/js/wc-gateway-ppec-generate-cart.js
Labels: [Status] Needs Review, [Type] Enhancement

#719 Update phpcs config and add Travis integration
  .gitattributes
  .gitignore
  .travis.yml
  composer.json
  phpcs.xml
  phpunit.xml
Labels: [Status] Needs Review

#658 Add locales and mapping
  includes/class-wc-gateway-ppec-settings.php
Labels: [Status] Needs Review

#736 #735: Update plugin links
  includes/class-wc-gateway-ppec-plugin.php
Labels: [Status] Needs Review

#740 Fixes `paypal.getFundingSources is not a function` console errors
  assets/js/wc-gateway-ppec-smart-payment-buttons.js
  includes/class-wc-gateway-ppec-cart-handler.php
Labels: Priority: CRITICAL, [Status] Ready to Merge

#720 [Coding Standards] Fix smells
  includes/abstracts/abstract-wc-gateway-ppec-client-credential.php
  includes/abstracts/abstract-wc-gateway-ppec-paypal-request-handler.php
  includes/abstracts/abstract-wc-gateway-ppec.php
  includes/class-wc-gateway-ppec-address.php
  includes/class-wc-gateway-ppec-admin-handler.php
  includes/class-wc-gateway-ppec-api-error.php
  includes/class-wc-gateway-ppec-cart-handler.php
  includes/class-wc-gateway-ppec-checkout-details.php
  includes/class-wc-gateway-ppec-checkout-handler.php
  includes/class-wc-gateway-ppec-client-credential-certificate.php
  includes/class-wc-gateway-ppec-client-credential-signature.php
  includes/class-wc-gateway-ppec-client.php
  includes/class-wc-gateway-ppec-gateway-loader.php
  includes/class-wc-gateway-ppec-ipn-handler.php
  includes/class-wc-gateway-ppec-ips-handler.php
  includes/class-wc-gateway-ppec-payment-details.php
  includes/class-wc-gateway-ppec-plugin.php
  includes/class-wc-gateway-ppec-privacy.php
  includes/class-wc-gateway-ppec-refund.php
  includes/class-wc-gateway-ppec-session-data.php
  includes/class-wc-gateway-ppec-settings.php
  includes/class-wc-gateway-ppec-with-paypal-addons.php
  includes/class-wc-gateway-ppec-with-paypal-credit.php
  includes/class-wc-gateway-ppec-with-spb-addons.php
  includes/class-wc-gateway-ppec-with-spb.php
  includes/exceptions/class-wc-gateway-ppec-api-exception.php
  includes/functions.php
  includes/settings/settings-ppec.php
  phpcs.xml
  woocommerce-gateway-paypal-express-checkout.php
Labels: [Status] Needs Review
