Repository woocommerce/woocommerce-gateway-paypal-express-checkout, pull requests merged in 2020-03, with the labels that each got.

#697 Only make the billing fields optional during an open PPEC session
  includes/class-wc-gateway-ppec-checkout-handler.php
Labels: Documentation

#677 Do not add discounts to total item amount and cause line item amount offset
  includes/class-wc-gateway-ppec-client.php
Labels: [Status] Needs Review

#659 Add translation tables for states of some countries including Japan
  includes/class-wc-gateway-ppec-address.php
Labels: [Status] Needs Review

#704 Exit early from js scripts before targeting nonexistent elements
  assets/js/wc-gateway-ppec-smart-payment-buttons.js
  includes/class-wc-gateway-ppec-cart-handler.php
Labels: [Status] Needs Review, [Type] Bug
