Repository woocommerce/woocommerce-gateway-paypal-express-checkout, pull requests merged in 2021-05, with the labels that each got.

#793 Only ensure session on single product pages
  includes/class-wc-gateway-ppec-cart-handler.php
Labels: priority: high, status: needs review

#869 Add hooks to change name/description of line items sent to PayPal
  includes/class-wc-gateway-ppec-client.php
Labels: status: needs review

#868 Bump WooCommerce requirement to 3.2.0
  includes/abstracts/abstract-wc-gateway-ppec.php
  includes/class-wc-gateway-ppec-plugin.php
  woocommerce-gateway-paypal-express-checkout.php
Labels: status: needs review

#771 Change the label and description of the PayPal Mark setting
  includes/settings/settings-ppec.php
Labels: priority: low, status: needs review, type: documentation

#870 Add BLIK and MercadoPago as funding methods
  includes/settings/settings-ppec.php
Labels: status: needs review
